services:
  - type: web
    name: swiftshield
    env: python
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "gunicorn backend.run:app"
    envVars:
      - key: FLASK_ENV
        value: production
